# Generated by Django 4.1.3 on 2022-11-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='cat',
            new_name='finch',
        ),
    ]
